-- GAMMERTEST 테이블생성
CREATE TABLE GAMMERTEST (
	ID NUMBER PRIMARY KEY NOT NULL,
	NAME VARCHAR2(200),
	CONTENT VARCHAR2(2000)
);

-- 데이터 가져오기
SELECT ID, NAME, CONTENT
		FROM GAMMERTEST 
		WHERE ID = 1;
		

		